### ISSUE TITLE
overflow-x: hidden does not work on most mobile browsers.

### ISSUE THREAD

**Issue by joearcher** [GroundXaero/bootstrap-easy-sidebar#2]
Which is why I included the media query in my pull request. Your current demo makes the whole visible page 250px wider when the sidebar is triggered on Chrome for android. Open the sidebar then scroll around to see what I mean.

**Comment by AndyCormack** [comment]
Fixed with a slightly different method, I wanted to keep the body scrolling sideways even on mobile as I felt it looked better and kept visual consistency.

Used

``` css
@media (max-width:  768px) {
    body.toggled {
        position: fixed;
    }
}
```

It does have the side effect of scrolling the page back to the top, but it only happens on mobile and chances are you're going to another page when you open the menu anyway.

If you come up with a more elegant solution than this let me know.
